version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.3.0

jobs:
  build_frontend:
    docker:
      - image: circleci/node:14.11.0
    environment:
      FULL_IMAGE_NAME: 545264965023.dkr.ecr.us-east-1.amazonaws.com/agme-frontend:latest
    working_directory: ~/majorproject-2-thurs-18-30-6/FrontEnd/frontend-react  
    steps:
      - checkout:
          path: ~/majorproject-2-thurs-18-30-6
      - setup_remote_docker
#       - run:
#           name: Setup common environment variables
#           command: |
#             echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
#             echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:latest"' >> $BASH_ENV
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
   
      - save_cache:
          paths:
          - node_modules
          - ~/.npm 
          - ~/.cache        
          key: v1-dependencies-{{ checksum "package.json" }}
    
      - run: npm test

      - run:
          name: Install dependencies for AWS
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
            sudo apt-get install python3-pip
            sudo pip3 install --upgrade awscli
      - run:
          name: Build image
          command: |
            docker build -t $FULL_IMAGE_NAME .
      - run:
          name: Push image
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 545264965023.dkr.ecr.us-east-1.amazonaws.com
            docker push $FULL_IMAGE_NAME
  build_backend:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      FULL_IMAGE_NAME: 545264965023.dkr.ecr.us-east-1.amazonaws.com/agme-backend:latest
    working_directory: ~/majorproject-2-thurs-18-30-6/BackEnd
    steps:
      - checkout:
          path: ~/majorproject-2-thurs-18-30-6
      - setup_remote_docker
#       - run:
#           name: Setup common environment variables
#           command: |
#             echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
#             echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:latest"' >> $BASH_ENV


      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
            # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: BackEnd-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
              - ~/.m2
          key: BackEnd-{{ checksum "pom.xml" }}

      - run: mvn package # run the actual tests

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
            # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
            path: target/surefire-reports

      - store_artifacts: # store the uberjar as an artifact
            # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
            path: target/BackEnd-0.0.1-SNAPSHOT.jar
        # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

      - run:
          name: Install dependencies for AWS
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
            sudo apt-get install python3-pip
            sudo pip3 install --upgrade awscli
      - run:
          name: Build image
          command: |
            docker build -t $FULL_IMAGE_NAME .
      - run:
          name: Push image
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 545264965023.dkr.ecr.us-east-1.amazonaws.com
            docker push $FULL_IMAGE_NAME
      
workflows:
  build-deploy-qa:
    jobs:
      - build_frontend:
          filters:
            branches:
              only: master
      - build_backend:
          filters:
            branches:
              only: master       
